/* ============================================================================
 * gp200tips.js -- info-bulles (attribut title) de l'interface, en francais et en anglais
 *
 * Deux parties :
 *   - ui    : un texte par controle ou indicateur, cle = identifiant d'usage (voir app.js, applyTips)
 *   - param : explication d'un parametre de module d'apres son nom (Gain, Mix, Rate, 125Hz...) ;
 *             param(name, lang) renvoie '' si le nom est inconnu (l'appelant affiche alors la plage seule).
 * Aucun acces au DOM : testable sous Node (tests/run_tips_tests.js verifie que les deux langues ont les memes cles
 * et que TOUS les parametres de la table des modeles ont une explication).
 * ========================================================================== */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.GP200TIPS = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  const ui = {
    fr: {
      // ---- bandeau du haut
      mode_new: "Génère les presets d'un morceau à partir d'une description : l'IA propose 3 variantes par section (rythmique, solo…).",
      mode_refine: "Modifie un preset existant en langage courant (« plus de gain, moins de reverb ») : seuls les points demandés changent.",
      open_prst: "Ouvre un ou plusieurs fichiers .prst de ton ordinateur. Tu peux aussi les glisser directement dans la page.",
      pedal_chip_off: "Connecte la pédale GP-200 en USB. Le navigateur te demande l'autorisation d'utiliser le MIDI (Chrome ou Edge requis).",
      pedal_chip_none: "La pédale n'est pas détectée : branche-la en USB et allume-la, puis clique ici pour actualiser.",
      lang_fr: "Interface en français",
      lang_en: "Switch the interface to English",
      // ---- zone de demande
      demande: "Décris le son voulu : artiste, titre, passage (rythmique, solo, clean…), ta guitare. Ctrl + Entrée lance la génération.",
      instr: "Dis en clair ce que tu veux changer sur le preset affiché. Ctrl + Entrée lance l'affinage.",
      example: "Utiliser cet exemple comme demande : ",
      go: "Envoie ta description à l'IA : elle identifie le rig du morceau et construit les presets (3 variantes par section).",
      go_refine: "Applique tes instructions au preset affiché. Le détail exact des changements apparaît dans la fenêtre « Résultat ».",
      stop: "Interrompt la requête en cours à l'IA.",
      ref_loaded: "Le preset sur lequel porteront tes instructions (celui choisi dans « Mes presets »).",
      // ---- bibliotheque
      lib_count: "Nombre de presets dans la liste.",
      lib_row: "Affiche ce preset dans le rack. Avec l'injection automatique, il est aussi envoyé sur le slot de travail de la pédale.",
      lib_row_variant: "Variante %s de la section : affiche ce preset dans le rack (avec l'injection automatique, il est aussi envoyé sur la pédale).",
      kind_gen: "Preset généré par l'IA à partir de ta description.",
      kind_open: "Preset ouvert depuis un fichier .prst de ton ordinateur.",
      kind_refine: "Preset affiné : version modifiée par l'IA d'après tes instructions (l'original est conservé).",
      kind_live: "Preset créé à partir de ce que tu as réglé en direct.",
      vfile: "Nom du fichier .prst correspondant.",
      badge_warn: "La somme de contrôle (checksum) du fichier est incorrecte : il est peut-être corrompu ou modifié à la main.",
      dl_all: "Télécharge tous les presets de ce résultat dans une archive .zip.",
      dl_one: "Télécharge le preset affiché au format .prst (importable dans l'éditeur Valeton ou dans GP-200 Studio).",
      // ---- options de generation
      opts: "Réglages facultatifs de la génération : structure du morceau, micros de ta guitare, recherche web.",
      role_auto: "L'IA choisit elle-même les sections (rythmique, clean, solo…) selon le morceau.",
      role_clean: "Clean : son clair, sans saturation. Clique pour l'ajouter à la structure ; l'ordre des clics est l'ordre des sections (4 maximum).",
      role_crunch: "Crunch : légère saturation, son rythmique mordant. Clique pour l'ajouter à la structure ; l'ordre des clics est l'ordre des sections (4 maximum).",
      role_disto: "Disto : forte saturation (rythmique lourde). Clique pour l'ajouter à la structure ; l'ordre des clics est l'ordre des sections (4 maximum).",
      role_lead: "Lead : son de solo, plus présent et plus fort pour passer devant le groupe. Clique pour l'ajouter à la structure ; l'ordre des clics est l'ordre des sections (4 maximum).",
      pickup: "Type de micros de ta guitare : l'IA en tient compte pour régler le gain et l'égalisation.",
      web: "L'IA cherche sur le web le matériel et les réglages réellement utilisés sur le morceau, pour un résultat plus fidèle (indisponible avec OpenRouter).",
      // ---- rack
      slot_empty: "%s : emplacement vide dans ce preset. Clique pour le sélectionner, puis choisis un modèle dans l'éditeur du module.",
      slot_off: "%s : charge ou génère un preset pour voir ses réglages ici.",
      // ---- onglets / fenetres
      tab_result: "Détail du preset affiché : variante choisie (angle, écoute) ou liste exacte des changements d'un affinage.",
      tab_pedal: "Envoie le preset sur un slot de la pédale par USB, et montre ce que la pédale annonce (journal).",
      tab_ctrl: "Affectations CTRL : quels modules chacun des 8 interrupteurs CTRL du preset allume ou éteint d'un seul appui.",
      tab_tune: "Harmonise le volume de plusieurs presets : la page mesure le niveau (LUFS) pendant que tu joues et règle le volume.",
      tab_log: "Journal détaillé des échanges avec l'IA pour la dernière requête (utile en cas d'erreur).",
      pop_close: "Ferme cette fenêtre (touche Échap).",
      setup_close: "Ferme la fenêtre de connexion à l'IA.",
      sdot: "Voyant d'activité : allumé pendant qu'une requête à l'IA est en cours.",
      sdot_tab: "Une opération est en cours.",
      notice_x: "Masque ce message.",
      // ---- connexion a l'IA
      provider: "Service d'IA utilisé. Ta clé reste dans ce navigateur et n'est envoyée qu'à ce service.",
      model: "Modèle d'IA utilisé pour générer et affiner. « Actualiser la liste » interroge le service pour voir les modèles disponibles.",
      refresh: "Interroge le service d'IA pour récupérer la liste à jour des modèles disponibles.",
      apikey: "Colle ici ta clé d'API. Elle reste sur cet ordinateur et n'est envoyée qu'au service choisi.",
      key_toggle: "Affiche ou masque la clé saisie.",
      get_key: "Ouvre la page du service où créer ta clé d'API (nouvel onglet).",
      key_link: "Ouvre Google AI Studio, où l'on crée une clé Gemini (nouvel onglet).",
      or_login: "Ouvre OpenRouter pour autoriser GP-200 Studio ; tu reviens ici avec la clé déjà remplie.",
      remember: "Garde la clé dans ce navigateur pour ne pas la ressaisir. À décocher sur un ordinateur partagé.",
      setup_ok: "Valide et ferme. Nécessite une clé d'API.",
      // ---- module
      ed_model: "Change le modèle (l'effet ou l'ampli) de ce module. Les réglages repartent des valeurs par défaut du nouveau modèle.",
      ed_send: "Renvoie ce module entier à la pédale (modèle, état et tous les réglages), utile si l'écran et la pédale ne concordent plus.",
      ed_save: "Ouvre la fenêtre Pédale pour enregistrer durablement ce preset dans un slot de la pédale.",
      param_num: "Tape une valeur exacte, ou utilise le curseur à côté.",
      // ---- CTRL
      ctrl_cell: "Coché : un appui sur CTRL %s allume ou coupe le module « %s ».",
      ctrl_send: "Ouvre la fenêtre Pédale pour envoyer ce preset (avec ses CTRL) sur la pédale.",
      // ---- pedale
      pedal_connect: "Connecte la pédale GP-200 en USB. Le navigateur te demande l'autorisation d'utiliser le MIDI (Chrome ou Edge requis).",
      pedal_port: "Port MIDI de la pédale à utiliser quand plusieurs sont détectés.",
      pedal_retry: "Cherche à nouveau la pédale (après l'avoir branchée ou allumée).",
      pedal_bank: "Numéro du slot de la pédale (1 à 64). Le preset sera écrit dans ce slot.",
      pedal_letter: "Lettre du slot : chaque numéro contient 4 patchs A, B, C et D.",
      pedal_one: "Écrit le preset affiché dans le slot choisi. Son contenu actuel sera écrasé (confirmation demandée).",
      pedal_three: "Écrit les 3 variantes de la section dans trois slots consécutifs A, B et C. Leur contenu actuel sera écrasé (confirmation demandée).",
      pedal_yes: "Confirme : le contenu actuel du ou des slots est définitivement remplacé.",
      cancel: "Annule sans rien envoyer à la pédale.",
      pd_log: "Les derniers messages reçus de la pédale, en hexadécimal. Utile pour diagnostiquer, ou à joindre à un rapport de bug.",
      pd_log_copy: "Copie ce journal dans le presse-papiers.",
      pd_resend: "Réécrit le preset affiché dans le slot de travail pour que la pédale et l'écran soient de nouveau identiques.",
      pstate: "État de la liaison USB avec la pédale.",
      pled: "Voyant vert : pédale détectée.",
      // ---- slot de travail
      inj_bank: "Numéro (1 à 64) du slot de travail, celui qui reçoit les presets pendant que tu les essaies.",
      inj_letter: "Lettre (A à D) du slot de travail.",
      inj_auto: "Si coché, chaque preset que tu sélectionnes ou génères est écrit tout seul dans le slot de travail. Sinon, il faut cliquer sur « Injecter ».",
      listen_chk: "Garde le port MIDI ouvert pour suivre ce que tu fais sur la pédale (module coupé, volume, changement de patch). À décocher pour utiliser l'éditeur Valeton en même temps.",
      inj_ok: "Valide ce slot de travail et ferme la fenêtre.",
      // ---- harmonisation
      tune_open: "Ouvre le formulaire de réglage du volume d'un lot de presets.",
      tune_pedal: "Connecte la pédale GP-200 en USB : elle reçoit chaque preset pendant la mesure.",
      tune_audio: "Autorise le navigateur à écouter une entrée audio : la page mesure le volume qui sort de la pédale (cartes son ou GP-200 en USB).",
      tune_audio_sel: "Entrée audio à mesurer. Choisis la pédale GP-200 si elle apparaît (elle sort du son en USB).",
      tune_audio_refresh: "Relit la liste des entrées audio disponibles.",
      tune_bank: "Numéro (1 à 64) du slot de travail : chaque preset du lot y est écrit à tour de rôle. Son contenu est écrasé.",
      tune_letter: "Lettre (A à D) du slot de travail du lot.",
      tune_type: "Normal vise −16 LUFS (rythmique, clean), Lead vise −11 LUFS (solo, plus fort) : c'est le volume que la mesure cherche à atteindre.",
      tune_up_down: "Réordonner ou retirer ce preset du lot (l'ordre de la liste est l'ordre de mesure).",
      tune_open_files: "Ouvre des fichiers .prst (plusieurs à la fois) : ils rejoignent directement le lot.",
      tune_add_all: "Ajoute au lot tous les presets de la liste qui n'y sont pas encore.",
      tune_clear: "Retire tous les presets du lot (ils restent dans ta liste « Mes presets »).",
      tune_add_sum: "Presets de ta liste qui ne sont pas encore dans le lot.",
      tune_add: "Ajoute ce preset à la fin du lot.",
      tune_start: "Démarre la mesure : demande confirmation avant d'écrire dans le slot de travail. Nécessite la pédale, une entrée audio et au moins un preset.",
      tune_yes: "Confirme : le contenu actuel du slot de travail est remplacé et la mesure commence.",
      tune_zip: "Télécharge tous les presets harmonisés de ce lot dans une archive .zip.",
      t_pause: "Fige la mesure pour souffler ou changer quelque chose ; « Reprendre » relance.",
      t_resend: "Réécrit le preset en cours dans le slot de travail (si la pédale ne suit plus ou a été touchée).",
      t_prev: "Revient au preset précédent du lot pour le mesurer à nouveau.",
      t_next: "Passe au preset suivant du lot ; au dernier, termine l'harmonisation.",
      t_keep: "Applique tout de suite la correction calculée d'après le volume mesuré, sans attendre la stabilisation automatique.",
      t_stop: "Arrête l'harmonisation. Les presets déjà validés restent à jour dans la page.",
      t_gauge: "Jauge : écart entre le volume mesuré et la cible. Centre = pile sur la cible.",
      t_meter: "Mesure en LUFS : momentané (400 ms), court terme (3 s), intégré (depuis le début), et écart à la cible.",
      tune_row: "Preset en cours / état du lot.",
      // ---- instruments d'etat
      mstate: "État du module : clique sur le module dans le rack pour l'allumer ou le couper.",
      count: "Nombre de presets dans la liste.",
    },
    en: {
      mode_new: "Generate a song's presets from a description: the AI proposes 3 variants per section (rhythm, lead…).",
      mode_refine: "Change an existing preset in plain words (“more gain, less reverb”): only what you ask for changes.",
      open_prst: "Open one or more .prst files from your computer. You can also drop them straight onto the page.",
      pedal_chip_off: "Connect the GP-200 pedal over USB. The browser asks permission to use MIDI (Chrome or Edge required).",
      pedal_chip_none: "The pedal isn't detected: plug it in over USB and switch it on, then click here to refresh.",
      lang_fr: "Interface en français",
      lang_en: "Switch the interface to English",
      demande: "Describe the sound you want: artist, song, part (rhythm, lead, clean…), your guitar. Ctrl + Enter starts the generation.",
      instr: "Say in plain words what you want to change on the displayed preset. Ctrl + Enter starts the refinement.",
      example: "Use this example as your request: ",
      go: "Send your description to the AI: it identifies the song's rig and builds the presets (3 variants per section).",
      go_refine: "Apply your instructions to the displayed preset. The exact list of changes appears in the “Result” window.",
      stop: "Interrupt the current request to the AI.",
      ref_loaded: "The preset your instructions will apply to (the one selected in “My presets”).",
      lib_count: "Number of presets in the list.",
      lib_row: "Show this preset in the rack. With auto-injection on, it is also sent to the pedal's working slot.",
      lib_row_variant: "Variant %s of the section: show this preset in the rack (with auto-injection on, it is also sent to the pedal).",
      kind_gen: "Preset generated by the AI from your description.",
      kind_open: "Preset opened from a .prst file on your computer.",
      kind_refine: "Refined preset: a version changed by the AI from your instructions (the original is kept).",
      kind_live: "Preset created from what you adjusted live.",
      vfile: "Name of the matching .prst file.",
      badge_warn: "The file's checksum is wrong: it may be corrupted or hand-edited.",
      dl_all: "Download every preset of this result in a .zip archive.",
      dl_one: "Download the displayed preset as a .prst file (importable in the Valeton editor or in GP-200 Studio).",
      opts: "Optional generation settings: song structure, your guitar's pickups, web search.",
      role_auto: "The AI picks the sections (rhythm, clean, lead…) itself, based on the song.",
      role_clean: "Clean: clear sound, no distortion. Click to add it to the structure; click order is section order (4 max).",
      role_crunch: "Crunch: light distortion, biting rhythm sound. Click to add it to the structure; click order is section order (4 max).",
      role_disto: "Dist: heavy distortion (heavy rhythm). Click to add it to the structure; click order is section order (4 max).",
      role_lead: "Lead: solo sound, more present and louder to sit above the band. Click to add it to the structure; click order is section order (4 max).",
      pickup: "Your guitar's pickup type: the AI uses it to set gain and EQ.",
      web: "The AI searches the web for the gear and settings actually used on the song, for a more faithful result (not available with OpenRouter).",
      slot_empty: "%s: empty slot in this preset. Click to select it, then pick a model in the module editor.",
      slot_off: "%s: load or generate a preset to see its settings here.",
      tab_result: "Details of the displayed preset: chosen variant (angle, listening notes) or the exact list of changes from a refinement.",
      tab_pedal: "Send the preset to a pedal slot over USB, and see what the pedal reports (log).",
      tab_ctrl: "CTRL assignments: which modules each of the preset's 8 CTRL switches turns on or off with one press.",
      tab_tune: "Match the volume of several presets: the page measures the level (LUFS) while you play and sets the volume.",
      tab_log: "Detailed exchange with the AI for the last request (useful when something fails).",
      pop_close: "Close this window (Esc key).",
      setup_close: "Close the AI connection window.",
      sdot: "Activity light: on while a request to the AI is running.",
      sdot_tab: "An operation is running.",
      notice_x: "Dismiss this message.",
      provider: "AI service to use. Your key stays in this browser and is only sent to this service.",
      model: "AI model used to generate and refine. “Refresh list” asks the service which models are available.",
      refresh: "Ask the AI service for the up-to-date list of available models.",
      apikey: "Paste your API key here. It stays on this computer and is only sent to the chosen service.",
      key_toggle: "Show or hide the key you typed.",
      get_key: "Open the service's page where you create your API key (new tab).",
      key_link: "Open Google AI Studio, where a Gemini key is created (new tab).",
      or_login: "Open OpenRouter to authorise GP-200 Studio; you come back here with the key already filled in.",
      remember: "Keep the key in this browser so you don't retype it. Untick on a shared computer.",
      setup_ok: "Confirm and close. Needs an API key.",
      ed_model: "Change this module's model (the effect or amp). Settings start over from the new model's defaults.",
      ed_send: "Send this whole module to the pedal again (model, state and every setting), useful if the screen and the pedal no longer match.",
      ed_save: "Open the Pedal window to store this preset permanently in a pedal slot.",
      param_num: "Type an exact value, or use the slider next to it.",
      ctrl_cell: "Ticked: pressing CTRL %s turns the module “%s” on or off.",
      ctrl_send: "Open the Pedal window to send this preset (with its CTRL assignments) to the pedal.",
      pedal_connect: "Connect the GP-200 pedal over USB. The browser asks permission to use MIDI (Chrome or Edge required).",
      pedal_port: "MIDI port of the pedal to use when several are detected.",
      pedal_retry: "Look for the pedal again (after plugging it in or switching it on).",
      pedal_bank: "Pedal slot number (1 to 64). The preset is written into this slot.",
      pedal_letter: "Slot letter: each number holds 4 patches, A, B, C and D.",
      pedal_one: "Write the displayed preset into the chosen slot. Its current content is overwritten (confirmation asked).",
      pedal_three: "Write the section's 3 variants into three consecutive slots A, B and C. Their current content is overwritten (confirmation asked).",
      pedal_yes: "Confirm: the current content of the slot(s) is permanently replaced.",
      cancel: "Cancel without sending anything to the pedal.",
      pd_log: "The latest messages received from the pedal, in hexadecimal. Useful for diagnosis, or to attach to a bug report.",
      pd_log_copy: "Copy this log to the clipboard.",
      pd_resend: "Rewrite the displayed preset into the working slot so the pedal and the screen match again.",
      pstate: "State of the USB link with the pedal.",
      pled: "Green light: pedal detected.",
      inj_bank: "Number (1 to 64) of the working slot, the one that receives presets while you try them out.",
      inj_letter: "Letter (A to D) of the working slot.",
      inj_auto: "When ticked, every preset you select or generate is written to the working slot automatically. Otherwise you have to click “Inject”.",
      listen_chk: "Keep the MIDI port open to follow what you do on the pedal (module bypassed, volume, patch change). Untick to use the Valeton editor at the same time.",
      inj_ok: "Confirm this working slot and close the window.",
      tune_open: "Open the form to set the volume of a batch of presets.",
      tune_pedal: "Connect the GP-200 pedal over USB: it receives each preset during the measurement.",
      tune_audio: "Let the browser listen to an audio input: the page measures the volume coming out of the pedal (sound card or GP-200 over USB).",
      tune_audio_sel: "Audio input to measure. Pick the GP-200 if it is listed (it outputs sound over USB).",
      tune_audio_refresh: "Reload the list of available audio inputs.",
      tune_bank: "Number (1 to 64) of the working slot: each preset of the batch is written there in turn. Its content is overwritten.",
      tune_letter: "Letter (A to D) of the batch's working slot.",
      tune_type: "Normal aims for −16 LUFS (rhythm, clean), Lead aims for −11 LUFS (solo, louder): this is the volume the measurement tries to reach.",
      tune_up_down: "Reorder or remove this preset from the batch (list order is measuring order).",
      tune_open_files: "Open .prst files (several at once): they go straight into the batch.",
      tune_add_all: "Add to the batch every preset of the list that isn't in it yet.",
      tune_clear: "Remove every preset from the batch (they stay in your “My presets” list).",
      tune_add_sum: "Presets from your list that aren't in the batch yet.",
      tune_add: "Add this preset at the end of the batch.",
      tune_start: "Start the measurement: asks for confirmation before writing to the working slot. Needs the pedal, an audio input and at least one preset.",
      tune_yes: "Confirm: the working slot's current content is replaced and the measurement starts.",
      tune_zip: "Download every matched preset of this batch in a .zip archive.",
      t_pause: "Freeze the measurement to take a break or change something; “Resume” restarts it.",
      t_resend: "Rewrite the current preset into the working slot (if the pedal no longer follows or was touched).",
      t_prev: "Go back to the previous preset of the batch to measure it again.",
      t_next: "Move on to the next preset of the batch; on the last one, finish the matching.",
      t_keep: "Apply the correction computed from the measured volume right now, without waiting for the automatic stabilisation.",
      t_stop: "Stop the matching. Presets already validated stay up to date on the page.",
      t_gauge: "Gauge: gap between the measured volume and the target. Centre = right on target.",
      t_meter: "LUFS measurement: momentary (400 ms), short-term (3 s), integrated (since the start), and gap to the target.",
      tune_row: "Current preset / batch state.",
      mstate: "Module state: click the module in the rack to turn it on or bypass it.",
      count: "Number of presets in the list.",
    },
  };

  // ---------------------------------------------------------------- parametres de module
  // [francais, anglais]
  const P = {
    'Volume': ['Niveau de sortie de ce module.', 'Output level of this module.'],
    'Gain': ["Quantité de saturation (drive) : plus c'est haut, plus le son sature.", 'Amount of distortion (drive): the higher, the more it saturates.'],
    'Treble': ["Aigus : brillance et définition de l'attaque.", 'Treble: brightness and pick definition.'],
    'Bass': ['Graves : rondeur et poids du son.', 'Bass: roundness and weight of the sound.'],
    'Middle': ['Médiums : corps du son et place dans le mix.', 'Mids: body of the sound and its place in the mix.'],
    'Presence': ["Présence : aigus extrêmes de l'ampli, ouverture et mordant.", "Presence: the amp's top end, openness and bite."],
    'Mix': ["Dosage entre le son d'origine et l'effet : 0 = pas d'effet, 100 = effet maximal.", 'Blend between the original sound and the effect: 0 = no effect, 100 = full effect.'],
    'Sync': ['Synchronisation sur le tempo (tap) de la pédale : 0 = désactivée, 1 = activée.', "Sync to the pedal's tap tempo: 0 = off, 1 = on."],
    'Trail': ["Queue de l'effet : 1 = elle continue de s'éteindre naturellement quand on coupe le module, 0 = coupure nette.", 'Effect tail: 1 = it decays naturally when the module is bypassed, 0 = it cuts off.'],
    'Tone': ['Timbre de ce module : plus bas = plus sombre, plus haut = plus brillant.', 'Tone of this module: lower = darker, higher = brighter.'],
    'Feedback': ["Part du signal renvoyée à l'entrée de l'effet : plus c'est haut, plus il y a de répétitions ou de résonance (négatif : phase inversée).", "Amount of signal fed back into the effect: the higher, the more repeats or resonance (negative: inverted phase)."],
    'Rate': ["Vitesse de la modulation.", 'Speed of the modulation.'],
    'Time': ['Durée entre deux répétitions, en millisecondes.', 'Time between repeats, in milliseconds.'],
    'Depth': ['Profondeur (amplitude) de la modulation.', 'Depth (amount) of the modulation.'],
    'Decay': ['Durée de la réverbération (longueur de sa queue).', 'Length of the reverb (how long its tail lasts).'],
    'Pre Delay': ["Délai avant le début de l'effet, en millisecondes.", 'Delay before the effect starts, in milliseconds.'],
    'Mode': ['Variante de fonctionnement de ce modèle (voir la plage de valeurs).', "Operating variant of this model (see the value range)."],
    'Mod': ['Légère modulation interne qui rend la réverbe ou le delay plus vivant.', 'Slight internal modulation that makes the reverb or delay livelier.'],
    'Attack': ["Vitesse de réaction au début d'une note.", 'How fast it reacts at the start of a note.'],
    'Range': ["Étendue de l'effet (amplitude du balayage ou de la variation).", 'Span of the effect (sweep or variation amount).'],
    'Bright': ["Interrupteur de brillance : 1 = ajoute des aigus, 0 = désactivé.", 'Brightness switch: 1 = adds treble, 0 = off.'],
    'Q': ['Résonance du filtre : plus c\'est haut, plus il est étroit et piqué.', 'Filter resonance: the higher, the narrower and sharper.'],
    'Level': ['Niveau du signal retardé (les répétitions).', 'Level of the delayed signal (the repeats).'],
    'Position': ["Position de la pédale d'effet, du talon (0) à la pointe (100).", "Position of the effect pedal, from heel (0) to toe (100)."],
    'Low Damp': ['Amortissement des graves dans la réverbe : plus haut = queue moins chargée en graves.', 'Low-frequency damping in the reverb: higher = tail with less bass.'],
    'Hi Damp': ['Amortissement des aigus dans la réverbe : plus haut = queue plus sombre.', 'High-frequency damping in the reverb: higher = darker tail.'],
    'High Damp': ['Amortissement des aigus dans la réverbe : plus haut = queue plus sombre.', 'High-frequency damping in the reverb: higher = darker tail.'],
    'Blend': ["Mélange entre le son d'origine et le son traité.", 'Blend between the original and the processed sound.'],
    'Tone Cut': ["Atténuation des aigus de l'ampli : plus c'est haut, plus le son est sombre.", "Treble cut of the amp: the higher, the darker the sound."],
    'Threshold': ["Seuil de déclenchement : niveau à partir duquel l'effet agit.", 'Trigger threshold: the level from which the effect acts.'],
    'Release': ["Vitesse de retour à la normale après l'action de l'effet.", 'How fast it returns to normal after the effect has acted.'],
    'Dry': ["Niveau du signal d'origine, non traité.", 'Level of the original, unprocessed signal.'],
    'Wet': ['Niveau du signal traité (effet).', 'Level of the processed (effect) signal.'],
    'Sustain': ['Durée de maintien de la note : plus haut = note tenue plus longtemps.', 'Note sustain: higher = the note is held longer.'],
    'Ratio': ["Taux de réduction appliqué au signal au-delà du seuil.", 'Amount of reduction applied to the signal above the threshold.'],
    'Low Cut': ['Filtre passe-haut : coupe les graves en dessous de cette fréquence (Hz).', 'High-pass filter: cuts the bass below this frequency (Hz).'],
    'High Cut': ['Filtre passe-bas : coupe les aigus au-dessus de cette fréquence (Hz).', 'Low-pass filter: cuts the treble above this frequency (Hz).'],
    'Low': ['Niveau de la bande des graves.', 'Level of the low band.'],
    'High': ['Niveau de la bande des aigus.', 'Level of the high band.'],
    'Hi Pitch': ['Transposition de la voix aiguë, en demi-tons.', 'Transposition of the high voice, in semitones.'],
    'Low Pitch': ['Transposition de la voix grave, en demi-tons.', 'Transposition of the low voice, in semitones.'],
    'Hi Vol': ['Volume de la voix aiguë.', 'Volume of the high voice.'],
    'Low Vol': ['Volume de la voix grave.', 'Volume of the low voice.'],
    'Bit': ['Résolution du signal : plus on réduit, plus le son est dégradé (lo-fi).', 'Signal resolution: the lower it goes, the more degraded (lo-fi) the sound.'],
    'Freq': ["Fréquence de l'effet.", 'Frequency of the effect.'],
    'Key': ["Tonalité de référence de l'harmoniseur (0 à 11 = les 12 notes).", "Reference key of the harmonizer (0 to 11 = the 12 notes)."],
    'Smooth Mode': ["Option de lissage de l'harmoniseur : 0 = désactivé, 1 = activé.", 'Harmonizer smoothing option: 0 = off, 1 = on.'],
    'Fuzz': ['Quantité de fuzz (saturation très compressée).', 'Amount of fuzz (heavily compressed distortion).'],
    'Filter': ["Réglage du filtre de l'effet.", "Setting of the effect's filter."],
    'Drive': ['Quantité de saturation (drive).', 'Amount of distortion (drive).'],
    'Activate': ["Interrupteur de l'effet : 0 = désactivé, 1 = activé.", 'Effect switch: 0 = off, 1 = on.'],
    'Balance': ['Équilibre entre les deux parties du préampli.', 'Balance between the two sections of the preamp.'],
    'EQ Freq': ["Fréquence centrale du correcteur intégré à l'ampli.", "Centre frequency of the amp's built-in EQ."],
    'EQ Q': ['Largeur du correcteur intégré : plus haut = bande plus étroite.', 'Width of the built-in EQ: higher = narrower band.'],
    'EQ Gain': ['Gain du correcteur intégré : renforce ou atténue la fréquence choisie.', 'Gain of the built-in EQ: boosts or cuts the chosen frequency.'],
    'Lo End': ["Niveau des extrêmes graves de la réverbe (négatif = atténue).", "Level of the reverb's lowest frequencies (negative = cut)."],
    'Hi End': ["Niveau des extrêmes aigus de la réverbe (négatif = atténue).", "Level of the reverb's highest frequencies (negative = cut)."],
    'Clipping': ["Niveau d'écrêtage du signal.", 'Signal clipping level.'],
    '+3dB': ['Ajoute 3 dB de niveau : 0 = non, 1 = oui.', 'Adds 3 dB of level: 0 = off, 1 = on.'],
    'Hold': ["Temps de maintien avant que le gate se referme, en millisecondes.", 'Hold time before the gate closes, in milliseconds.'],
    'Hysteresis': ["Écart entre les seuils d'ouverture et de fermeture du gate : évite qu'il papillonne.", 'Gap between the gate opening and closing thresholds: stops it from chattering.'],
    'Shape': ["Forme du son (réglage de timbre propre à ce modèle).", 'Shape of the sound (a tone control specific to this model).'],
    'Body': ["Corps de la guitare acoustique simulée.", 'Body of the simulated acoustic guitar.'],
    'Top': ["Brillance de la table de la guitare acoustique simulée.", 'Top-end sparkle of the simulated acoustic guitar.'],
    'Sense': ["Sensibilité : réaction à l'attaque de la corde.", 'Sensitivity: how it reacts to the pick attack.'],
    'Sens': ["Sensibilité : réaction à l'attaque de la corde.", 'Sensitivity: how it reacts to the pick attack.'],
    'Detune': ['Désaccord entre le signal et sa copie (valeur négative ou positive).', 'Detuning between the signal and its copy (negative or positive).'],
    'Krush': ["Écrasement du son (effet bit-crusher).", 'Sound crushing (bit-crusher effect).'],
    'Hi Cut': ['Coupe les aigus : plus haut = son plus sombre.', 'Cuts the treble: higher = darker sound.'],
    'Lo Cut': ['Coupe les graves : plus haut = son plus fin.', 'Cuts the bass: higher = thinner sound.'],
    'Fine': ["Réglage fin de la fréquence (valeur négative ou positive).", 'Fine tuning of the frequency (negative or positive).'],
    'Saturation': ['Quantité de saturation appliquée au signal.', 'Amount of saturation applied to the signal.'],
    'Harmony': ["Active l'harmonie : 0 = désactivée, 1 = activée.", 'Turns the harmony on: 0 = off, 1 = on.'],
    'Interval': ["Intervalle de la voix harmonisée (voir la plage de valeurs).", 'Interval of the harmonized voice (see the value range).'],
    'Interval 1': ["Intervalle de la première voix harmonisée (voir la plage de valeurs).", 'Interval of the first harmonized voice (see the value range).'],
    'Interval 2': ["Intervalle de la seconde voix harmonisée (voir la plage de valeurs).", 'Interval of the second harmonized voice (see the value range).'],
    'Fat': ["Option qui épaissit le son : 0 = désactivée, 1 = activée.", 'Option that thickens the sound: 0 = off, 1 = on.'],
    'Air': ["Option qui ajoute de l'air dans les aigus : 0 = désactivée, 1 = activée.", 'Option that adds air to the top end: 0 = off, 1 = on.'],
    'Voice': ["Caractère (voicing) de l'overdrive.", 'Character (voicing) of the overdrive.'],
    'Gate': ['Seuil du noise gate intégré : plus haut = il coupe plus tôt le souffle.', "Threshold of the built-in noise gate: higher = it cuts the noise earlier."],
    'Contour': ['Forme du creux de médiums.', 'Shape of the mid scoop.'],
    'Lo-mid': ['Médiums graves : niveau de la zone médium basse.', 'Low mids: level of the lower mid range.'],
    'Hi-mid': ['Médiums aigus : niveau de la zone médium haute.', 'High mids: level of the upper mid range.'],
    'Master': ["Volume général de l'ampli ou de la pédale.", 'Master volume of the amp or pedal.'],
    'Mid Freq': ['Fréquence centrale des médiums.', 'Centre frequency of the mids.'],
    'Tight': ["Resserre les graves pour un son plus précis.", 'Tightens the low end for a more precise sound.'],
    'Output': ['Niveau de sortie.', 'Output level.'],
    'Color': ['Couleur du phaser : 0 ou 1 = deux caractères différents.', 'Phaser colour: 0 or 1 = two different characters.'],
    'Bias': ['Polarisation du trémolo : change la forme de la modulation.', 'Tremolo bias: changes the shape of the modulation.'],
    'Curve': ["Forme de la courbe de l'effet (voir la plage de valeurs).", 'Curve shape of the effect (see the value range).'],
    'EQ': ["Active l'égaliseur de la pédale : 0 = désactivé, 1 = activé.", "Turns the pedal's EQ on: 0 = off, 1 = on."],
    'Char': ['Caractère de l\'ampli : 0 ou 1 = deux voicings.', "Amp character: 0 or 1 = two voicings."],
    'Input': ["Niveau d'entrée : pousse plus ou moins l'étage d'entrée.", 'Input level: drives the input stage more or less.'],
    'Edge': ["Mordant de l'attaque.", 'Bite of the attack.'],
    'Midrange': ['Position du réglage de médiums (voir la plage de valeurs).', 'Mid-range switch position (see the value range).'],
    'Time R%': ["Temps du canal droit, en pourcentage de celui du gauche (effet stéréo).", 'Right-channel time as a percentage of the left one (stereo effect).'],
    'Spread': ["Écart stéréo : décale les répétitions entre gauche et droite.", 'Stereo spread: offsets the repeats between left and right.'],
    'Dly Mix': ["Mélange du delay de l'effet.", "Mix of the effect's delay."],
    'Ring Mix': ["Mélange du modulateur en anneau de l'effet.", "Mix of the effect's ring modulator."],
    'Wow &': ['Pleurage et scintillement (wow & flutter) de la bande.', 'Tape wow and flutter.'],
    'Age': ['Vieillissement de la bande : plus haut = son plus usé.', 'Tape ageing: higher = more worn sound.'],
    'Scrape': ['Frottement de la bande sur la tête de lecture.', 'Tape scraping on the head.'],
    'Crush': ['Écrasement lo-fi des répétitions.', 'Lo-fi crushing of the repeats.'],
    'Latch': ['Maintien des répétitions du delay cassé.', 'How long the broken delay holds its repeats.'],
    'Cut': ['Coupure des répétitions du delay cassé.', 'How much the broken delay chops its repeats.'],
    'Pitch': ['Transposition des répétitions, en demi-tons.', 'Transposition of the repeats, in semitones.'],
    'Slice': ['Découpage des répétitions (voir la plage de valeurs).', 'Slicing of the repeats (see the value range).'],
    'Direction': ['Sens de lecture des répétitions (négatif ou positif).', 'Playback direction of the repeats (negative or positive).'],
    'Smooth': ['Lissage des transitions de hauteur.', 'Smoothing of the pitch transitions.'],
  };
  // familles de noms
  const FAM = [
    [/^(\d+(?:\.\d+)?)(k?)Hz$/, (m, fr) => fr ? `Bande d'égalisation autour de ${m[1]}${m[2] ? ' k' : ' '}Hz : valeur positive = renforce cette fréquence, négative = l'atténue.`
      : `EQ band around ${m[1]}${m[2] ? ' k' : ' '}Hz: positive value = boosts this frequency, negative = cuts it.`],
    [/^Step (\d)$/, (m, fr) => fr ? `Valeur de l'étape ${m[1]} du séquenceur de filtre.` : `Value of step ${m[1]} of the filter sequencer.`],
    [/^Gain (\d)$/, (m, fr) => fr ? `Gain de l'étage ${m[1]} : quantité de saturation de cet étage.` : `Gain of stage ${m[1]}: amount of distortion of that stage.`],
    [/^Tone (\d)$/, (m, fr) => fr ? `Timbre de l'étage ${m[1]}.` : `Tone of stage ${m[1]}.`],
    [/^Mix ([AB])$/, (m, fr) => fr ? `Niveau du delay ${m[1]}.` : `Level of delay ${m[1]}.`],
    [/^Time ([AB])$/, (m, fr) => fr ? `Temps du delay ${m[1]}, en millisecondes.` : `Time of delay ${m[1]}, in milliseconds.`],
    [/^Feedback ([AB])$/, (m, fr) => fr ? `Répétitions du delay ${m[1]} (négatif : phase inversée).` : `Repeats of delay ${m[1]} (negative: inverted phase).`],
    [/^Sync ([AB])$/, (m, fr) => fr ? `Synchronisation du delay ${m[1]} sur le tempo : 0 = désactivée, 1 = activée.` : `Sync of delay ${m[1]} to the tempo: 0 = off, 1 = on.`],
    [/^(Flg|Trm|Phs|Pan|Sweep|Time) Sync$/, (m, fr) => fr ? 'Synchronisation sur le tempo (tap) : 0 = désactivée, 1 = activée.' : 'Sync to the tap tempo: 0 = off, 1 = on.'],
    [/^(Flg|Trm|Phs|Pan|Sweep) Rate$/, (m, fr) => fr ? `Vitesse de ${LABEL_FR[m[1]]}.` : `Speed of the ${LABEL_EN[m[1]]}.`],
    [/^(Flg|Trm|Phs|Pan|Sweep) Depth$/, (m, fr) => fr ? `Profondeur de ${LABEL_FR[m[1]]}.` : `Depth of the ${LABEL_EN[m[1]]}.`],
    [/^Depth ([LCR])$/, (m, fr) => fr ? `Profondeur de modulation, voie ${{ L: 'gauche', C: 'centre', R: 'droite' }[m[1]]}.` : `Modulation depth, ${{ L: 'left', C: 'centre', R: 'right' }[m[1]]} voice.`],
    [/^(Low|High) Oct$/, (m, fr) => fr ? `Niveau de l'octave ${m[1] === 'Low' ? 'grave' : 'aiguë'}.` : `Level of the ${m[1] === 'Low' ? 'low' : 'high'} octave.`],
  ];
  const LABEL_FR = { Flg: 'le flanger', Trm: 'le trémolo', Phs: 'le phaser', Pan: 'le panoramique', Sweep: "l'écho à balayage" };
  const LABEL_EN = { Flg: 'flanger', Trm: 'tremolo', Phs: 'phaser', Pan: 'auto-pan', Sweep: 'sweep echo' };

  /** Explication d'un parametre d'apres son nom ('' si inconnu). lang = 'fr' | 'en'. */
  function param(name, lang) {
    const fr = lang !== 'en';
    if (Object.prototype.hasOwnProperty.call(P, name)) return P[name][fr ? 0 : 1];
    for (const [re, fn] of FAM) { const m = re.exec(name); if (m) return fn(m, fr); }
    return '';
  }
  /** Info-bulle complete d'un parametre : nom, explication, plage et valeur par defaut. */
  function paramTip(p, lang) {
    const fr = lang !== 'en';
    const lo = Math.min(p.min, p.max), hi = Math.max(p.min, p.max);
    const fmt = v => { const x = Math.round(v * 100) / 100; return fr ? String(x).replace('.', ',') : String(x); };
    const what = param(p.name, lang) || (fr ? 'Réglage de ce modèle.' : 'Setting of this model.');
    const range = (fr ? 'Plage : ' : 'Range: ') + fmt(lo) + ' – ' + fmt(hi) + (p.default !== undefined && p.default !== null ? (fr ? ' · par défaut : ' : ' · default: ') + fmt(p.default) : '');
    return p.name + ' : ' + what + '\n' + range;
  }

  return { ui, param, paramTip, paramNames: Object.keys(P) };
});
